### ISSUE TITLE
Field PCC.Series not found in config

### ISSUE THREAD

**Issue by ahmedwahdan** [aul12/CubeMxCMake#1]
I was trying to generate Cmake file for project using STM32F746NG board and got this erro
`Field PCC.Series not found in config`

**Comment by aul12** [comment]
Which version of CubeMX are you using?

**Comment by ahmedwahdan** [comment]
5.6.1

**Comment by aul12** [comment]
I think i fixed the issue, see the pull request #2 and the branch Fix#1. Could you check if the script works on this branch with your setup?
