### ISSUE TITLE
Linker script

### ISSUE THREAD

**Issue by Zataras** [aul12/CubeMxCMake#3]
Hi,

Do you know why I got no linker script in CubeMx project?

-- The C compiler identification is GNU 9.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:45 (add_executable):
  Cannot find source file:

    /home/xx/ws/yy/lowLevel/STM32F1_FLASH.ld

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:45 (add_executable):
  No SOURCES given to target: yy.elf

**Comment by aul12** [comment]
Did you follow the [guide](http://aul12.me/embedded/2019/05/27/cubemx-cmake.html) on how to export the project? Is there any linker script (file ending `.ld`)?

**Comment by Zataras** [comment]
Hi, yes I've followed the guide.
Yes, I've found the script under another name: "STM32F103RBTx_FLASH.ld" so maybe something has changes in CubeMx 5.6.0. Maybe its name as script input would be good idea.

Thanks for quick response!
